name: Update Credly Badges

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with Credly Badges
        uses: jd-35656/readme-credly-badges@v1
        with:
          credly_username: 'devin-clements'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          badge_ids: '148ad3da-8081-4a3c-9104-5638291ea4ee,0ddca255-336e-47a4-964f-019fe99a9693,7444fde9-e234-489b-8e77-91881833ecf2'
          badge_width: '120'
          badge_height: '120'

